// ===================================================
// DATA: Algorithm definitions
// ===================================================
const ALGORITHMS = [
  {
    id: 'dfs',
    name: 'DFS',
    fullName: 'Depth First Search',
    vname: 'Tìm kiếm theo chiều sâu',
    desc: 'Khám phá đồ thị bằng cách đi sâu nhất có thể theo mỗi nhánh trước khi quay lại.',
    color: '#F59E0B',
    bg: 'rgba(245,158,11,0.12)',
    complexity: 'O(V + E)',
    difficulty: 1,
    tags: ['Đệ quy', 'Ngăn xếp', 'Thăm nút'],
    features: ['Đồ thị có hướng/vô hướng', 'Phát hiện chu trình', 'Thành phần liên thông'],
    supportsNeg: true,
    weighted: false,
    icon: '🔍',
    directed: false
  },
  {
    id: 'bfs',
    name: 'BFS',
    fullName: 'Breadth First Search',
    vname: 'Tìm kiếm theo chiều rộng',
    desc: 'Thăm tất cả các nút ở cùng mức trước khi đi sâu hơn, dùng hàng đợi.',
    color: '#3B82F6',
    bg: 'rgba(59,130,246,0.12)',
    complexity: 'O(V + E)',
    difficulty: 1,
    tags: ['Hàng đợi', 'Đường ngắn nhất', 'Mức độ'],
    features: ['Đường ngắn nhất (unweighted)', 'Duyệt theo lớp', 'Thành phần liên thông'],
    supportsNeg: true,
    weighted: false,
    icon: '🌊',
    directed: false
  },
  {
    id: 'dijkstra',
    name: 'Dijkstra',
    fullName: "Dijkstra's Shortest Path",
    vname: 'Đường đi ngắn nhất Dijkstra',
    desc: 'Tìm đường đi ngắn nhất từ một nguồn đến tất cả các đỉnh. Không hỗ trợ cạnh âm.',
    color: '#10B981',
    bg: 'rgba(16,185,129,0.12)',
    complexity: 'O((V+E) log V)',
    difficulty: 2,
    tags: ['Hàng đợi ưu tiên', 'Tham lam', 'Trọng số'],
    features: ['Đường ngắn nhất có trọng số', 'Chỉ cạnh dương', 'Priority Queue'],
    supportsNeg: false,
    weighted: true,
    icon: '🎯',
    directed: true,
    needsTarget: true
  },
  {
    id: 'bellman',
    name: 'Ford-Bellman',
    fullName: 'Bellman-Ford Algorithm',
    vname: 'Thuật toán Bellman-Ford',
    desc: 'Tìm đường ngắn nhất, hỗ trợ cạnh âm và phát hiện chu trình âm.',
    color: '#EF4444',
    bg: 'rgba(239,68,68,0.12)',
    complexity: 'O(V × E)',
    difficulty: 3,
    tags: ['Lập trình động', 'Cạnh âm', 'Chu trình âm'],
    features: ['Cạnh âm OK', 'Phát hiện chu trình âm', 'Tối ưu từng vòng lặp'],
    supportsNeg: true,
    weighted: true,
    icon: '⚡',
    directed: true,
    needsTarget: false
  },
  {
    id: 'prim',
    name: "Prim's MST",
    fullName: "Prim's Minimum Spanning Tree",
    vname: 'Cây khung nhỏ nhất Prim',
    desc: 'Xây dựng cây khung nhỏ nhất bằng cách mở rộng từ một đỉnh nguồn.',
    color: '#8B5CF6',
    bg: 'rgba(139,92,246,0.12)',
    complexity: 'O((V+E) log V)',
    difficulty: 2,
    tags: ['MST', 'Tham lam', 'Cây khung'],
    features: ['Cây khung nhỏ nhất', 'Đồ thị liên thông', 'Hàng đợi ưu tiên'],
    supportsNeg: false,
    weighted: true,
    icon: '🌳',
    directed: false
  }
];

// ===================================================
// PSEUDOCODE definitions
// ===================================================
const PSEUDOCODES = {
  dfs: [
    'procedure DFS(graph, start):',
    '  stack ← [start]',
    '  visited ← {}',
    '  while stack is not empty:',
    '    node ← stack.pop()',
    '    if node not in visited:',
    '      mark node as visited',
    '      for each neighbor of node:',
    '        if neighbor not visited:',
    '          stack.push(neighbor)',
  ],
  bfs: [
    'procedure BFS(graph, start):',
    '  queue ← [start]',
    '  visited ← {start}',
    '  while queue is not empty:',
    '    node ← queue.dequeue()',
    '    process node',
    '    for each neighbor of node:',
    '      if neighbor not visited:',
    '        visited.add(neighbor)',
    '        queue.enqueue(neighbor)',
  ],
  dijkstra: [
    'procedure DIJKSTRA(graph, src):',
    '  dist[src] ← 0; dist[others] ← ∞',
    '  pq ← [(0, src)]',
    '  while pq is not empty:',
    '    (d, u) ← pq.extract_min()',
    '    if d > dist[u]: continue',
    '    mark u as visited',
    '    for each edge (u, v, w):',
    '      if dist[u] + w < dist[v]:',
    '        dist[v] ← dist[u] + w',
    '        pq.insert((dist[v], v))',
  ],
  bellman: [
    'procedure BELLMAN_FORD(graph, src):',
    '  dist[src] ← 0; dist[others] ← ∞',
    '  for i ← 1 to |V| - 1:',
    '    for each edge (u, v, w):',
    '      if dist[u] + w < dist[v]:',
    '        dist[v] ← dist[u] + w',
    '  for each edge (u, v, w):',
    '    if dist[u] + w < dist[v]:',
    '      return "Negative cycle detected!"',
    '  return dist',
  ],
  prim: [
    'procedure PRIM(graph, start):',
    '  inMST ← {start}',
    '  mst_edges ← []',
    '  pq ← all edges from start',
    '  while pq not empty:',
    '    (w, u, v) ← pq.extract_min()',
    '    if v in inMST: continue',
    '    add (u, v, w) to mst_edges',
    '    inMST.add(v)',
    '    for each edge (v, x, w2):',
    '      if x not in inMST: pq.insert((w2, v, x))',
  ],
};
